FROM node:18-alpine

# 타임존 설정
RUN apk add --no-cache tzdata
ENV TZ=Asia/Seoul

WORKDIR /app

# ARG (빌드 타임 환경 변수)
ARG DATABASE_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG JWT_SECRET
ARG NOTION_TOKEN

# ENV (실행 시 환경 변수)
ENV DATABASE_URL=$DATABASE_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
ENV GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV JWT_SECRET=$JWT_SECRET
ENV NOTION_TOKEN=$NOTION_TOKEN
ENV NEXT_DISABLE_LIGHTNINGCSS=true

# 패키지 설치
COPY package.json package-lock.json ./
COPY prisma ./prisma/
RUN npm install
RUN npx prisma generate

# 앱 복사 및 빌드
COPY . .
RUN sed -i '/DATABASE_URL/d' .env || true
RUN npm run build

EXPOSE 5000
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start"]
