version: '3'
services:
  developweb:
    build:
      context: .
      args:
        - ENV_FILE=.env.temp
    container_name: developWeb
    restart: always
    env_file:
      - .env.local
    ports:
      - "5000:5000"

networks:
  default:
    external:
      name: dockerdb_default
