const editorTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  paragraph: 'mb-4',
  quote: 'border-l-4 border-neutral-300 dark:border-neutral-700 pl-4 italic my-4',
  heading: {
    h1: 'text-4xl font-bold mb-4',
    h2: 'text-3xl font-bold mb-3',
    h3: 'text-2xl font-bold mb-2',
    h4: 'text-xl font-bold mb-2',
    h5: 'text-lg font-bold mb-1',
  },
  list: {
    nested: {
      listitem: 'list-none',
    },
    ol: 'list-decimal ml-4 my-4',
    ul: 'list-disc ml-4 my-4',
    listitem: 'mb-1',
  },
  image: 'max-w-full h-auto',
  link: 'text-blue-600 dark:text-blue-400 underline hover:no-underline',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-neutral-100 dark:bg-neutral-800 px-1 py-0.5 rounded font-mono text-sm',
  },
  code: 'bg-neutral-900 text-neutral-100 p-4 rounded-lg my-4 font-mono text-sm overflow-x-auto',
  codeHighlight: {
    atrule: 'text-purple-400',
    attr: 'text-blue-400',
    boolean: 'text-orange-400',
    builtin: 'text-cyan-400',
    cdata: 'text-gray-400',
    char: 'text-green-400',
    class: 'text-yellow-400',
    'class-name': 'text-yellow-400',
    comment: 'text-gray-500',
    constant: 'text-orange-400',
    deleted: 'text-red-400',
    doctype: 'text-gray-400',
    entity: 'text-orange-400',
    function: 'text-blue-400',
    important: 'text-red-400',
    inserted: 'text-green-400',
    keyword: 'text-purple-400',
    namespace: 'text-yellow-400',
    number: 'text-orange-400',
    operator: 'text-cyan-400',
    prolog: 'text-gray-400',
    property: 'text-blue-400',
    punctuation: 'text-gray-400',
    regex: 'text-green-400',
    selector: 'text-yellow-400',
    string: 'text-green-400',
    symbol: 'text-orange-400',
    tag: 'text-red-400',
    url: 'text-blue-400',
    variable: 'text-cyan-400',
  },
};

export default editorTheme;